"""empty message

Revision ID: baed50a42efb
Revises: 
Create Date: 2024-10-26 11:38:40.508517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'baed50a42efb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('photo', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('apuestas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('event_name', sa.String(length=100), nullable=False),
    sa.Column('prediction', sa.String(length=100), nullable=False),
    sa.Column('odds', sa.Numeric(), nullable=True),
    sa.Column('amount_bet', sa.Numeric(), nullable=True),
    sa.Column('stake', sa.Numeric(), nullable=True),
    sa.Column('resultado', sa.String(length=20), nullable=True),
    sa.Column('result_amount', sa.Numeric(), nullable=True),
    sa.Column('result_units', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('estadisticas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('unit_value', sa.Numeric(), nullable=True),
    sa.Column('money_bet', sa.Numeric(), nullable=True),
    sa.Column('money_won', sa.Numeric(), nullable=True),
    sa.Column('profit', sa.Numeric(), nullable=True),
    sa.Column('played_units', sa.Numeric(), nullable=True),
    sa.Column('profit_units', sa.Numeric(), nullable=True),
    sa.Column('yield_percentage', sa.Numeric(), nullable=True),
    sa.Column('total_bets', sa.Integer(), nullable=True),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.Column('losses', sa.Integer(), nullable=True),
    sa.Column('draws', sa.Integer(), nullable=True),
    sa.Column('success_rate', sa.Numeric(), nullable=True),
    sa.Column('average_odds', sa.Numeric(), nullable=True),
    sa.Column('average_stake', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('estadisticas')
    op.drop_table('apuestas')
    op.drop_table('user')
    # ### end Alembic commands ###
